/* eslint-disable no-undef */
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require("google-protobuf");
var goog = jspb;
var global = Function("return this")();

var proto_identifier_pb = require("../proto/identifier_pb.js");
goog.exportSymbol("proto.github.com.tankangliang.gollab.Message", null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.tankangliang.gollab.Message = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    null,
    proto.github.com.tankangliang.gollab.Message.oneofGroups_
  );
};
goog.inherits(proto.github.com.tankangliang.gollab.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.com.tankangliang.gollab.Message.displayName =
    "proto.github.com.tankangliang.gollab.Message";
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.github.com.tankangliang.gollab.Message.oneofGroups_ = [[2, 5]];

/**
 * @enum {number}
 */
proto.github.com.tankangliang.gollab.Message.DataCase = {
  DATA_NOT_SET: 0,
  IDENTIFIER: 2,
  OUTPUT: 5,
};

/**
 * @return {proto.github.com.tankangliang.gollab.Message.DataCase}
 */
proto.github.com.tankangliang.gollab.Message.prototype.getDataCase = function () {
  return /** @type {proto.github.com.tankangliang.gollab.Message.DataCase} */ (jspb.Message.computeOneofCase(
    this,
    proto.github.com.tankangliang.gollab.Message.oneofGroups_[0]
  ));
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.github.com.tankangliang.gollab.Message.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.github.com.tankangliang.gollab.Message.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.github.com.tankangliang.gollab.Message} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.github.com.tankangliang.gollab.Message.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        type: jspb.Message.getFieldWithDefault(msg, 1, ""),
        identifier:
          (f = msg.getIdentifier()) &&
          proto_identifier_pb.Identifier.toObject(includeInstance, f),
        output: jspb.Message.getFieldWithDefault(msg, 5, ""),
        roomid: jspb.Message.getFieldWithDefault(msg, 3, ""),
        userid: jspb.Message.getFieldWithDefault(msg, 4, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.tankangliang.gollab.Message}
 */
proto.github.com.tankangliang.gollab.Message.deserializeBinary = function (
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.tankangliang.gollab.Message();
  return proto.github.com.tankangliang.gollab.Message.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.tankangliang.gollab.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.tankangliang.gollab.Message}
 */
proto.github.com.tankangliang.gollab.Message.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setType(value);
        break;
      case 2:
        var value = new proto_identifier_pb.Identifier();
        reader.readMessage(
          value,
          proto_identifier_pb.Identifier.deserializeBinaryFromReader
        );
        msg.setIdentifier(value);
        break;
      case 5:
        var value = /** @type {string} */ (reader.readString());
        msg.setOutput(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setRoomid(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setUserid(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.tankangliang.gollab.Message.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.github.com.tankangliang.gollab.Message.serializeBinaryToWriter(
    this,
    writer
  );
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.tankangliang.gollab.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.tankangliang.gollab.Message.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getIdentifier();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_identifier_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(5, f);
  }
  f = message.getRoomid();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
};

/**
 * optional string type = 1;
 * @return {string}
 */
proto.github.com.tankangliang.gollab.Message.prototype.getType = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/** @param {string} value */
proto.github.com.tankangliang.gollab.Message.prototype.setType = function (
  value
) {
  jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional Identifier identifier = 2;
 * @return {?proto.github.com.tankangliang.gollab.Identifier}
 */
proto.github.com.tankangliang.gollab.Message.prototype.getIdentifier = function () {
  return /** @type{?proto.github.com.tankangliang.gollab.Identifier} */ (jspb.Message.getWrapperField(
    this,
    proto_identifier_pb.Identifier,
    2
  ));
};

/** @param {?proto.github.com.tankangliang.gollab.Identifier|undefined} value */
proto.github.com.tankangliang.gollab.Message.prototype.setIdentifier = function (
  value
) {
  jspb.Message.setOneofWrapperField(
    this,
    2,
    proto.github.com.tankangliang.gollab.Message.oneofGroups_[0],
    value
  );
};

proto.github.com.tankangliang.gollab.Message.prototype.clearIdentifier = function () {
  this.setIdentifier(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.com.tankangliang.gollab.Message.prototype.hasIdentifier = function () {
  return jspb.Message.getField(this, 2) != null;
};

/**
 * optional string output = 5;
 * @return {string}
 */
proto.github.com.tankangliang.gollab.Message.prototype.getOutput = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};

/** @param {string} value */
proto.github.com.tankangliang.gollab.Message.prototype.setOutput = function (
  value
) {
  jspb.Message.setOneofField(
    this,
    5,
    proto.github.com.tankangliang.gollab.Message.oneofGroups_[0],
    value
  );
};

proto.github.com.tankangliang.gollab.Message.prototype.clearOutput = function () {
  jspb.Message.setOneofField(
    this,
    5,
    proto.github.com.tankangliang.gollab.Message.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.com.tankangliang.gollab.Message.prototype.hasOutput = function () {
  return jspb.Message.getField(this, 5) != null;
};

/**
 * optional string roomID = 3;
 * @return {string}
 */
proto.github.com.tankangliang.gollab.Message.prototype.getRoomid = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/** @param {string} value */
proto.github.com.tankangliang.gollab.Message.prototype.setRoomid = function (
  value
) {
  jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional string userID = 4;
 * @return {string}
 */
proto.github.com.tankangliang.gollab.Message.prototype.getUserid = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};

/** @param {string} value */
proto.github.com.tankangliang.gollab.Message.prototype.setUserid = function (
  value
) {
  jspb.Message.setProto3StringField(this, 4, value);
};

goog.object.extend(exports, proto.github.com.tankangliang.gollab);
