/* eslint-disable no-undef */
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require("google-protobuf");
var goog = jspb;
var global = Function("return this")();

goog.exportSymbol("proto.github.com.tankangliang.gollab.Triplet", null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.tankangliang.gollab.Triplet = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.tankangliang.gollab.Triplet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.com.tankangliang.gollab.Triplet.displayName =
    "proto.github.com.tankangliang.gollab.Triplet";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.github.com.tankangliang.gollab.Triplet.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.github.com.tankangliang.gollab.Triplet.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.github.com.tankangliang.gollab.Triplet} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.github.com.tankangliang.gollab.Triplet.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        path: jspb.Message.getFieldWithDefault(msg, 1, 0),
        site: jspb.Message.getFieldWithDefault(msg, 2, ""),
        count: jspb.Message.getFieldWithDefault(msg, 3, 0),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.tankangliang.gollab.Triplet}
 */
proto.github.com.tankangliang.gollab.Triplet.deserializeBinary = function (
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.tankangliang.gollab.Triplet();
  return proto.github.com.tankangliang.gollab.Triplet.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.tankangliang.gollab.Triplet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.tankangliang.gollab.Triplet}
 */
proto.github.com.tankangliang.gollab.Triplet.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readUint32());
        msg.setPath(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setSite(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readUint32());
        msg.setCount(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.tankangliang.gollab.Triplet.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.github.com.tankangliang.gollab.Triplet.serializeBinaryToWriter(
    this,
    writer
  );
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.tankangliang.gollab.Triplet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.tankangliang.gollab.Triplet.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getPath();
  if (f !== 0) {
    writer.writeUint32(1, f);
  }
  f = message.getSite();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeUint32(3, f);
  }
};

/**
 * optional uint32 path = 1;
 * @return {number}
 */
proto.github.com.tankangliang.gollab.Triplet.prototype.getPath = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};

/** @param {number} value */
proto.github.com.tankangliang.gollab.Triplet.prototype.setPath = function (
  value
) {
  jspb.Message.setProto3IntField(this, 1, value);
};

/**
 * optional string site = 2;
 * @return {string}
 */
proto.github.com.tankangliang.gollab.Triplet.prototype.getSite = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/** @param {string} value */
proto.github.com.tankangliang.gollab.Triplet.prototype.setSite = function (
  value
) {
  jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional uint32 count = 3;
 * @return {number}
 */
proto.github.com.tankangliang.gollab.Triplet.prototype.getCount = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};

/** @param {number} value */
proto.github.com.tankangliang.gollab.Triplet.prototype.setCount = function (
  value
) {
  jspb.Message.setProto3IntField(this, 3, value);
};

goog.object.extend(exports, proto.github.com.tankangliang.gollab);
