package sample

import (
	"math/rand"

	"github.com/tankangliang/gollab/pb"
)

// NewRoomRequest returns a new sample room request with a random ID
func NewRoomRequest() *pb.CreateRoomRequest {
	roomReq := &pb.CreateRoomRequest{
		Id: randomString(5),
	}

	return roomReq
}

// NewTriplet return a new sample triplet generated by the client
func NewTriplet() *pb.Triplet {

	triplet := &pb.Triplet{
		Path:  uint32(rand.Int31()),
		Site:  randomString(5),
		Count: uint32(rand.Int31()),
	}

	return triplet
}

// NewIdentifier returns a new sample Identifier with value and triplet field with one triplet
func NewIdentifier() *pb.Message_Identifier {
	identifier := &pb.Message_Identifier{
		Identifier: &pb.Identifier{
			Value:    string(options[rand.Intn(len(options))]),
			Triplets: []*pb.Triplet{NewTriplet()},
		},
	}

	return identifier
}

// NewMessage returns a sample Message with type of action and identifier
func NewMessage() *pb.Message {
	message := &pb.Message{
		Data: NewIdentifier(),
	}
	i := rand.Intn(2)
	switch i {
	case 0:
		message.Type = "insert"
	case 1:
		message.Type = "delete"
	}

	return message
}
